[package]
name = "base64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_hex = { path="../custom_hex"}

[dev-dependencies]
hex = "0.4.3"
