[package]
name = "single_byte_xor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed_xor = { path = "../fixed_xor" }
custom_hex = { path = "../custom_hex" }
